### ISSUE TITLE
GSoC 2015: Meta bug for "Support Ed25519/EdDSA"

### ISSUE THREAD

**Issue by iseki-masaya** [open-keychain/open-keychain#1283]
@Valodim @dschuermann 

This issue is for my GSoC project.

Project Abstract: This project improve the security and performance of OpenKeychain due to two reasons. For security, the support of EdDSA is very important to enhance the security of OpenKeychain. There are no proof that ECDSA satisfy EUF-CMA which is a theoretical security model. EdDSA is based on Schnorr signature. Schnorr signature is EUF-CMA secure in the random oracle model. For performance, EdDSA is faster than ECDSA in some point(e.g. key generation, verification, etc...).

- [ ]  #1279 Import fails with eddsa signature packet.
- [ ]  #1284 Implement Ed25519 operations.
- [ ]  #1285 Implement EdDSA.
- [ ]  #1332 Implementation plan.
- [x]  #1336 Fix test cases in pg.

**Comment by Valodim** [comment]
Check out issue #1279. BouncyCastle right now throws an exception when it encounters an eddsa signature, which breaks our import routine on any key which has such a packet. Looking at the SignaturePacket class, it should be feasible to add compatibility for eddsa signatures so that they don't crash but simply can't be verified.
